# 请输入自己的appid和appsecret
oauth:
  wx:
    miniapp:
      appId: appId
      appSecret: appSecret
      url: https://api.weixin.qq.com/sns/jscode2session
    pub:
      appId: appId
      appSecret: appSecret
      url: https://api.weixin.qq.com/sns/oauth2/access_token

tfa:
  phone:
    dysms:
      # 阿里云短信 AccessKey ID
      appId: appId
      # 阿里云短信 AccessKey Secret
      appSecret: appSecret

spring:
  mail:
    host: smtp.qq.com
    # 邮箱地址
    username: email
    # 授权码
    password: password
